- name: Install nginx
  dnf:
    name: 'nginx'

- name: Create nexus.conf
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Check firewalld state
  shell: firewall-cmd --state
  register: firewall_state
  ignore_errors: yes
  changed_when: false
  check_mode: no

- name: Allow http
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  when: firewall_state.rc == 0

- name: set SELinux
  command: setsebool httpd_can_network_connect on -P
