ProxyRequests Off
ProxyPreserveHost On

<VirtualHost *:80>
  ServerName nexus.mosaos.local
  ServerAdmin admin@example.com

  AllowEncodedSlashes NoDecode

  ProxyPass / http://localhost:8081/ nocanon
  ProxyPassReverse / http://localhost:8081/
</VirtualHost>
